// components/Navpills/NavpillsTab.jsx
import CaptureGrid from "../Revogrid/CaptureGrid"

export default ({ Machines, Process, FailureCodes, ScrapCodes, Rates, ServerData }) => {
  const FormatName = (Name) => Name.replace("'", "").replace("-", "").split(" ").join("")

  return (
    <>
      <ul className="nav nav-pills" id="myTab" role="tablist">
        {Machines.map(({ MACHINE_NAME }, I) => {
          return (
            <li key={`${MACHINE_NAME}-${I}`} className="nav-item" role="presentation">
              <button className={`nav-link ${I === 0 && "active"}`} id={`${FormatName(MACHINE_NAME)}-${I}`} data-bs-toggle="pill" data-bs-target={`#${FormatName(MACHINE_NAME)}`} type="button" role="tab" aria-controls={FormatName(MACHINE_NAME)} aria-selected={I === 0 && "true"}>{MACHINE_NAME}</button>
            </li>
          )
        })}
      </ul>
      <div className="tab-content" id="myTabContent">
        {Machines.map(({ MACHINE_NAME }, I) => {
          return (
            <div key={`${MACHINE_NAME}-${I}`} className={`tab-pane fade ${I === 0 && "show active"}`} id={`${FormatName(MACHINE_NAME)}`} role="tabpanel" aria-labelledby={`${FormatName(MACHINE_NAME)}-${I}`} >
              <CaptureGrid MACHINE_NAME={MACHINE_NAME} PROCESS={Process} FAILURECODES={FailureCodes} SCRAPCODES={ScrapCodes} RATES={Rates} SERVERDATA={ServerData} />
            </div>
          )
        })}
      </div>
    </>
  )
}

// src/components/Navpills/NavpillsTab.svelte
<script>
	import CaptureGrid from '../Revogrid/CaptureGrid.svelte'
  export let Machines

  const FormatName = (Name) => Name.replace("'", "").replace("-","").split(" ").join("")
</script>

{#key Machines}
  <ul class="nav nav-pills" id="myTab" role="tablist">
  {#each Machines as { MACHINE_NAME }, I}
    <li class="nav-item" role="presentation">
      <button class="nav-link {I === 0 && "active"}" id="{FormatName(MACHINE_NAME)}-{I}" data-bs-toggle="pill" data-bs-target="#{FormatName(MACHINE_NAME)}" type="button" role="tab" aria-controls={FormatName(MACHINE_NAME)} aria-selected={I === 0 && "true"}>{MACHINE_NAME}</button>
    </li>
  {/each}
  </ul>

  <div class="tab-content" id="myTabContent">
    {#each Machines as { MACHINE_NAME, PROCESS }, I}
      <div class="tab-pane fade {I === 0 && "show active"}" id="{FormatName(MACHINE_NAME)}" role="tabpanel" aria-labelledby="{FormatName(MACHINE_NAME)}-{I}">
        <CaptureGrid MachineName={MACHINE_NAME} Process={PROCESS} />
      </div>
    {/each}
  </div>
{/key}
