// src/components/Navbar/DropdownItem.svelte
<script>
  import { CurrentPath } from '../../store'
  export let Title, Path
</script>

<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle {$CurrentPath.includes(Path) ? "active" : ""}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{Title}</a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    <slot></slot>
  </ul>
</li>

// components/Navbar/DropdownItem.jsx
import { useRouter } from "next/router"

export default ({ children, Title, Path }) => {
  let CurrentPath = useRouter().asPath

  return (
    <li>
      <a className={`nav-link dropdown-toggle ${CurrentPath?.includes(Path) ? "active" : ""}`} id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{Title}</a>
      <ul className="dropdown-menu" aria-labelledby="navbarDropdown">
        {children}
      </ul>
    </li>
  )
}
