// src/components/Navbar/Item.svelte
<script>
  import { CurrentPath } from '../../store'
  export let DropdownItem = false, href
</script>

{#if DropdownItem}
  <li>
    <a class="dropdown-item {href === $CurrentPath ? "active" : ""}" {href}>
      <slot></slot>
    </a>
  </li>
{:else}
  <li class="nav-item">
    <a class="nav-link {href === $CurrentPath ? "active" : ""}" aria-current="page" {href}>
      <slot></slot>
    </a>
  </li>
{/if}

// components/Navbar/Item.jsx
import Link from "next/link"
import { useRouter } from "next/router"

export default ({ children, DropdownItem = false, href}) => {
  let CurrentPath = useRouter().asPath

  if (DropdownItem) {
    return (
      <li>
        <Link href={href}>
          <a className={`dropdown-item ${href === CurrentPath ? "active" : ""}`}>
            {children}
          </a>
        </Link>
      </li>
    )
  }
  else {
    return (
      <li className="nav-item">
        <Link href={href}>
          <a className={`nav-link ${href === CurrentPath ? "active" : ""}`} aria-current="page">
            {children}
          </a>
        </Link>
      </li>
    )
  }
}
